[project]
name = "test_fts_project"
database = "test_fts_project.db"

[resource.searchable_docs]
description = "Searchable documents"
fragments = true

[resource.documents]
description = "Documents with auto-searchable fragments"
fragments = true

